In [1]:
# Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os
import time

# Import API key
from api_keys import g_key

In [2]:
# import csv from part 1 of homework
csv_w = "cities_submit.csv"
csv_weather = pd.read_csv(csv_w)
csv_weather

,Unnamed: 0,City #,City,Temp,Latitude,Longitude,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,1,castro,73.40,-24.7911,-50.0119,45,23,11.25,BR,1659618536
1,1,2,tuatapere,53.17,-46.1333,167.6833,87,100,7.52,NZ,1659618641
2,2,3,hermanus,63.81,-34.4187,19.2345,65,83,15.90,ZA,1659618641
3,3,4,saldanha,58.77,-33.0117,17.9442,65,48,11.86,ZA,1659618642
4,4,5,manokwari,77.14,-0.8667,134.0833,81,100,3.36,ID,1659618642
...,...,...,...,...,...,...,...,...,...,...,...
576,576,577,danilovka,87.15,50.3557,44.1168,34,62,9.51,RU,1659618847
577,577,578,sulangan,79.47,11.1373,123.7228,86,100,8.03,PH,1659618847
578,578,579,holme,81.97,56.1138,10.1725,74,72,9.04,DK,1659618847
579,579,580,cabinda,74.39,-5.5500,12.2000,70,37,11.72,AO,1659618848
580,580,581,araouane,99.84,18.9048,-3.5265,28,49,8.52,ML,1659618848

In [3]:
# configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# drop na values from weather csv and find max humidity for use in heat map
csv_weather = csv_weather.dropna()
csv_weather["Humidity"].max()

100

In [5]:
# Store 'Lat' and 'Lng' into  locations 
locations = csv_weather[["Latitude", "Longitude"]].astype(float)

In [6]:
# find humidity column, make series
humidity = csv_weather["Humidity"].astype(float)

In [7]:
 # Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# create a DF that has ideal weather conditions
df_ideal_temp = csv_weather.loc[(csv_weather["Temp"] >= 65) & (csv_weather["Temp"] <=75), :] 
df_ideal_wind= df_ideal_temp.loc[(df_ideal_temp["Wind Speed"] >= 5) & (df_ideal_temp["Wind Speed"] <=15), :] 
df_ideal = df_ideal_wind.loc[(df_ideal_wind["Cloudiness"] >= 0) & (df_ideal_wind["Cloudiness"] <=50), :] 
df_ideal

,Unnamed: 0,City #,City,Temp,Latitude,Longitude,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,1,castro,73.40,-24.7911,-50.0119,45,23,11.25,BR,1659618536
17,17,18,vaini,73.56,-21.2000,-175.2000,94,40,8.05,TO,1659618646
19,19,20,north platte,71.11,41.1239,-100.7654,77,0,11.01,US,1659618507
51,51,52,beira,74.39,-19.8436,34.8389,64,1,9.86,MZ,1659618657
56,56,57,kargasok,69.51,59.0556,80.8572,53,2,7.36,RU,1659618659
76,76,77,isangel,74.97,-19.5500,169.2667,89,6,6.13,VU,1659618667
78,78,79,makakilo city,73.72,21.3469,-158.0858,76,0,5.75,US,1659618282
163,163,164,nouadhibou,71.22,20.9310,-17.0347,92,9,10.69,MR,1659618699
180,180,181,le mars,65.35,42.7942,-96.1656,62,0,7.63,US,1659618705
184,184,185,kochki,72.25,54.3358,80.4806,36,3,11.23,RU,1659618707
195,195,196,mahebourg,73.69,-20.4081,57.7000,68,40,12.66,MU,1659618710
222,222,223,guerrero negro,68.61,27.9769,-114.0611,89,1,13.15,MX,1659618719
246,246,247,bambous virieux,73.65,-20.3428,57.7575,68,40,12.66,MU,1659618728
260,260,261,souillac,73.78,-20.5167,57.5167,68,40,12.66,MU,1659618732
283,283,284,saint-philippe,71.19,-21.3585,55.7679,78,28,11.74,RE,1659618742
308,308,309,roebourne,70.11,-20.7833,117.1333,37,5,7.23,AU,1659618751
385,385,386,srandakan,74.80,-7.9386,110.2506,88,9,6.46,ID,1659618196
401,401,402,saint-joseph,70.18,-21.3667,55.6167,76,41,11.70,RE,1659618272
402,402,403,umea,69.73,63.8284,20.2597,73,0,14.97,SE,1659618783
407,407,408,namibe,70.27,-15.1961,12.1522,61,0,14.14,AO,1659618785
443,443,444,rosarito,69.40,32.3333,-117.0333,83,27,5.86,MX,1659618800
450,450,451,soyo,73.17,-6.1349,12.3689,72,19,11.88,AO,1659618803
481,481,482,cap malheureux,73.47,-19.9842,57.6142,65,3,5.99,MU,1659618814
500,500,501,tadine,72.21,-21.5500,167.8833,90,38,11.03,NC,1659618821
532,532,533,canon city,68.63,38.4410,-105.2424,62,0,12.66,US,1659618831
541,541,542,grand gaube,73.80,-20.0064,57.6608,65,3,5.99,MU,1659618834
553,553,554,karratha,69.94,-20.7377,116.8463,33,2,12.53,AU,1659618244
579,579,580,cabinda,74.39,-5.5500,12.2000,70,37,11.72,AO,1659618848

In [9]:
# create new simplified DF to add hotel name to
hotel_df = df_ideal[["City", "Country", "Latitude", "Longitude"]]
hotel_df["Hotel Name"] = ""
hotel_df = hotel_df.reset_index()
del hotel_df["index"]
hotel_df

/var/folders/sp/6plkjdmn5qsb1910x_z26fnm0000gn/T/ipykernel_74288/4179913525.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

               City Country  Latitude  Longitude Hotel Name
0            castro      BR  -24.7911   -50.0119
1             vaini      TO  -21.2000  -175.2000
2      north platte      US   41.1239  -100.7654
3             beira      MZ  -19.8436    34.8389
4          kargasok      RU   59.0556    80.8572
5           isangel      VU  -19.5500   169.2667
6     makakilo city      US   21.3469  -158.0858
7        nouadhibou      MR   20.9310   -17.0347
8           le mars      US   42.7942   -96.1656
9            kochki      RU   54.3358    80.4806
10        mahebourg      MU  -20.4081    57.7000
11   guerrero negro      MX   27.9769  -114.0611
12  bambous virieux      MU  -20.3428    57.7575
13         souillac      MU  -20.5167    57.5167
14   saint-philippe      RE  -21.3585    55.7679
15        roebourne      AU  -20.7833   117.1333
16        srandakan      ID   -7.9386   110.2506
17     saint-joseph      RE  -21.3667    55.6167
18             umea      SE   63.8284    20.2597
19           namibe      AO  -15.1961    12.1522
20         rosarito      MX   32.3333  -117.0333
21             soyo      AO   -6.1349    12.3689
22   cap malheureux      MU  -19.9842    57.6142
23           tadine      NC  -21.5500   167.8833
24       canon city      US   38.4410  -105.2424
25      grand gaube      MU  -20.0064    57.6608
26         karratha      AU  -20.7377   116.8463
27          cabinda      AO   -5.5500    12.2000

In [10]:
# create empty list to be filled in following for loop 
hotel_name = []

In [11]:
# define base url and parameters for searching within the gmap api
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "keyword": "hotel",
    "types": "hotel",
    "key": g_key
}

# complete loop through the DF to find closest hotel to the provided city center coordinates
for index, row in hotel_df.iterrows():
    city = row["City"]
    print(f"Retrieving Results for {index}, the closest hotel to {city} is: ")
    lat = row["Latitude"]
    lng = row["Longitude"]
    params["location"] = f"{lat}, {lng}"
    response = requests.get(base_url, params = params)
    hotel_data = response.json()
    
    # try and except the results from the above API request and append the list with successful requests
    try:
        hotel_name.append(hotel_data["results"][0]["name"])
        print(f"{hotel_name[index]}")
    except:
        print("------------")
        print("No Hotel found") 
        print("------------")
        hotel_name.append("NO HOTEL NEARBY")

Retrieving Results for 0, the closest hotel to castro is:
Hotel Buganville Express
Retrieving Results for 1, the closest hotel to vaini is:
Dayspring Lodge
Retrieving Results for 2, the closest hotel to north platte is:
Fairfield Inn & Suites by Marriott North Platte
Retrieving Results for 3, the closest hotel to beira is:
Hotel Tivoli Beira
Retrieving Results for 4, the closest hotel to kargasok is:
Gostitsa Severyanka
Retrieving Results for 5, the closest hotel to isangel is:
Tanna Ikamir Guest House
Retrieving Results for 6, the closest hotel to makakilo city is:
Hampton Inn & Suites Oahu/Kapolei
Retrieving Results for 7, the closest hotel to nouadhibou is:
Hotel Delphin-Nouadhibou
Retrieving Results for 8, the closest hotel to le mars is:
Holiday Inn Express & Suites Le Mars, an IHG Hotel
Retrieving Results for 9, the closest hotel to kochki is:
Гостиница «Малина»
Retrieving Results for 10, the closest hotel to mahebourg is:
Holiday Inn Mauritius Mon Tresor
Retrieving Results for 11, the closest hotel to guerrero negro is:
The Halfway Inn
Retrieving Results for 12, the closest hotel to bambous virieux is:
La Case du Pêcheur
Retrieving Results for 13, the closest hotel to souillac is:
Shanti Maurice Resort & Spa
Retrieving Results for 14, the closest hotel to saint-philippe is:
Hôtel Les Embruns Du Baril
Retrieving Results for 15, the closest hotel to roebourne is:
Latitude20 Roebourne Village
Retrieving Results for 16, the closest hotel to srandakan is:
Puri Brata
Retrieving Results for 17, the closest hotel to saint-joseph is:
Gandalf Safari Camp
Retrieving Results for 18, the closest hotel to umea is:
Elite Hotel Mimer
Retrieving Results for 19, the closest hotel to namibe is:
Hotel Chik Chik Namibe
Retrieving Results for 20, the closest hotel to rosarito is:
Rosarito Beach Hotel
Retrieving Results for 21, the closest hotel to soyo is:
Kinwica Resort-Hotel (Soyo, Angola)
Retrieving Results for 22, the closest hotel to cap malheureux is:
LUX* Grand Baie
Retrieving Results for 23, the closest hotel to tadine is:
YEJELE BEACH MOTEL
Retrieving Results for 24, the closest hotel to canon city is:
Hampton Inn Canon City
Retrieving Results for 25, the closest hotel to grand gaube is:
Myra Seafront Suite 6
Retrieving Results for 26, the closest hotel to karratha is:
Karratha International Hotel
Retrieving Results for 27, the closest hotel to cabinda is:
Executive Paraíso Hotel

In [12]:
# add hotel list to the empty column in the dataframe
hotel_df["Hotel Name"] = hotel_name
hotel_df

,City,Country,Latitude,Longitude,Hotel Name
0,castro,BR,-24.7911,-50.0119,Hotel Buganville Express
1,vaini,TO,-21.2000,-175.2000,Dayspring Lodge
2,north platte,US,41.1239,-100.7654,Fairfield Inn & Suites by Marriott North Platte
3,beira,MZ,-19.8436,34.8389,Hotel Tivoli Beira
4,kargasok,RU,59.0556,80.8572,Gostitsa Severyanka
5,isangel,VU,-19.5500,169.2667,Tanna Ikamir Guest House
6,makakilo city,US,21.3469,-158.0858,Hampton Inn & Suites Oahu/Kapolei
7,nouadhibou,MR,20.9310,-17.0347,Hotel Delphin-Nouadhibou
8,le mars,US,42.7942,-96.1656,"Holiday Inn Express & Suites Le Mars, an IHG H..."
9,kochki,RU,54.3358,80.4806,Гостиница «Малина»
10,mahebourg,MU,-20.4081,57.7000,Holiday Inn Mauritius Mon Tresor
11,guerrero negro,MX,27.9769,-114.0611,The Halfway Inn
12,bambous virieux,MU,-20.3428,57.7575,La Case du Pêcheur
13,souillac,MU,-20.5167,57.5167,Shanti Maurice Resort & Spa
14,saint-philippe,RE,-21.3585,55.7679,Hôtel Les Embruns Du Baril
15,roebourne,AU,-20.7833,117.1333,Latitude20 Roebourne Village
16,srandakan,ID,-7.9386,110.2506,Puri Brata
17,saint-joseph,RE,-21.3667,55.6167,Gandalf Safari Camp
18,umea,SE,63.8284,20.2597,Elite Hotel Mimer
19,namibe,AO,-15.1961,12.1522,Hotel Chik Chik Namibe
20,rosarito,MX,32.3333,-117.0333,Rosarito Beach Hotel
21,soyo,AO,-6.1349,12.3689,"Kinwica Resort-Hotel (Soyo, Angola)"
22,cap malheureux,MU,-19.9842,57.6142,LUX* Grand Baie
23,tadine,NC,-21.5500,167.8833,YEJELE BEACH MOTEL
24,canon city,US,38.4410,-105.2424,Hampton Inn Canon City
25,grand gaube,MU,-20.0064,57.6608,Myra Seafront Suite 6
26,karratha,AU,-20.7377,116.8463,Karratha International Hotel
27,cabinda,AO,-5.5500,12.2000,Executive Paraíso Hotel

In [13]:
 # redisplay humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# create DF for LAT/LONG to be used in graph
locations_hotels = hotel_df[["Latitude", "Longitude"]].astype(float)
locations_hotels

    Latitude  Longitude
0   -24.7911   -50.0119
1   -21.2000  -175.2000
2    41.1239  -100.7654
3   -19.8436    34.8389
4    59.0556    80.8572
5   -19.5500   169.2667
6    21.3469  -158.0858
7    20.9310   -17.0347
8    42.7942   -96.1656
9    54.3358    80.4806
10  -20.4081    57.7000
11   27.9769  -114.0611
12  -20.3428    57.7575
13  -20.5167    57.5167
14  -21.3585    55.7679
15  -20.7833   117.1333
16   -7.9386   110.2506
17  -21.3667    55.6167
18   63.8284    20.2597
19  -15.1961    12.1522
20   32.3333  -117.0333
21   -6.1349    12.3689
22  -19.9842    57.6142
23  -21.5500   167.8833
24   38.4410  -105.2424
25  -20.0064    57.6608
26  -20.7377   116.8463
27   -5.5500    12.2000

In [15]:
# use info box template provided in starter code
info_box_template= """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [18]:
# create symbol layer for locations of hotels that meet ideal conditions
hotel_layer = gmaps.symbol_layer(
    locations_hotels, fill_color='rgba(150, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=7,
    info_box_content= hotel_info)
fig = gmaps.figure()
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
 # Create a combined map
fig = gmaps.figure()

fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))