In [1]:
# Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import gmaps
import os
import time

# Import API key
from api_keys import g_key

In [2]:
# import csv from part 1 of homework
csv_w = "cities_submit.csv"
csv_weather = pd.read_csv(csv_w)
csv_weather

,Unnamed: 0,City #,City,Temp,Latitude,Longitude,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,1,tasiilaq,40.69,65.6145,-37.6368,80,100,1.43,GL,1659617861
1,1,2,busselton,52.48,-33.6500,115.3333,73,100,8.34,AU,1659617861
2,2,3,cape town,64.38,-33.9258,18.4232,66,75,16.11,ZA,1659617643
3,3,4,onega,72.95,63.9061,38.1404,56,100,9.22,RU,1659617862
4,4,5,hami,96.46,42.8000,93.4500,12,88,9.75,CN,1659617862
...,...,...,...,...,...,...,...,...,...,...,...
547,547,548,torquay,73.69,50.4638,-3.5143,45,100,8.01,GB,1659618068
548,548,549,kokomo,73.35,40.4864,-86.1336,88,0,6.91,US,1659618069
549,549,550,lebedinyy,61.84,58.5167,125.5167,94,100,3.31,RU,1659618069
550,550,551,aloleng,83.07,16.1307,119.7824,76,100,4.81,PH,1659618070
551,551,552,cabedelo,74.07,-6.9811,-34.8339,75,9,17.18,BR,1659618070

In [3]:
# configure gmaps
gmaps.configure(api_key=g_key)

In [4]:
# drop na values from weather csv and find max humidity for use in heat map
csv_weather = csv_weather.dropna()
csv_weather["Humidity"].max()

100

In [5]:
# Store 'Lat' and 'Lng' into  locations 
locations = csv_weather[["Latitude", "Longitude"]].astype(float)

In [6]:
# find humidity column, make series
humidity = csv_weather["Humidity"].astype(float)

In [7]:
 # Create a humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# create a DF that has ideal weather conditions
df_ideal_temp = csv_weather.loc[(csv_weather["Temp"] >= 65) & (csv_weather["Temp"] <=75), :] 
df_ideal_wind= df_ideal_temp.loc[(df_ideal_temp["Wind Speed"] >= 5) & (df_ideal_temp["Wind Speed"] <=15), :] 
df_ideal = df_ideal_wind.loc[(df_ideal_wind["Cloudiness"] >= 0) & (df_ideal_wind["Cloudiness"] <=50), :] 
df_ideal

,Unnamed: 0,City #,City,Temp,Latitude,Longitude,Humidity,Cloudiness,Wind Speed,Country,Date
38,38,39,bambous virieux,73.65,-20.3428,57.7575,68,40,12.66,MU,1659617874
40,40,41,vaini,73.56,-21.2000,-175.2000,100,40,5.75,TO,1659617875
42,42,43,castro,73.40,-24.7911,-50.0119,45,23,11.25,BR,1659617875
60,60,61,winnemucca,69.44,40.9730,-117.7357,56,9,5.61,US,1659617882
142,142,143,sao joao da barra,73.49,-21.6403,-41.0511,73,14,8.68,BR,1659617913
149,149,150,east london,68.94,-33.0153,27.9116,68,0,12.66,ZA,1659617764
155,155,156,saint-philippe,71.19,-21.3585,55.7679,78,28,11.74,RE,1659617918
177,177,178,guerrero negro,68.61,27.9769,-114.0611,89,1,13.15,MX,1659617807
178,178,179,lincoln,69.35,40.8000,-96.6670,83,0,5.99,US,1659617926
183,183,184,mahebourg,73.69,-20.4081,57.7000,68,40,12.66,MU,1659617709
203,203,204,souillac,73.78,-20.5167,57.5167,68,40,12.66,MU,1659617935
229,229,230,bayevo,74.97,53.2833,80.7667,30,0,10.54,RU,1659617945
240,240,241,rebrikha,71.65,53.0733,82.3408,37,36,11.36,RU,1659617948
260,260,261,billings,74.52,45.7833,-108.5007,36,6,7.09,US,1659617927
264,264,265,grand gaube,73.80,-20.0064,57.6608,63,3,8.01,MU,1659617713
282,282,283,bowen,66.18,-20.0167,148.2333,86,0,6.24,AU,1659617961
284,284,285,namibe,70.27,-15.1961,12.1522,61,0,14.14,AO,1659617961
293,293,294,at-bashi,73.98,41.1702,75.8106,25,9,10.22,KG,1659617964
329,329,330,parabel,68.50,58.6978,81.4825,59,46,6.24,RU,1659617976
332,332,333,alyangula,73.13,-13.8483,136.4192,92,15,6.93,AU,1659617977
404,404,405,polovinnoye,74.46,54.7914,65.9864,53,1,8.68,RU,1659618000
410,410,411,kaltan,67.08,53.5347,87.2457,67,13,5.17,RU,1659618004
412,412,413,tshane,72.79,-24.0196,21.8684,22,0,6.44,BW,1659618005
444,444,445,plouzane,73.45,48.3833,-4.6167,49,40,12.66,FR,1659617915
526,526,527,ponta grossa,72.59,-25.0950,-50.1619,48,0,10.49,BR,1659618061
539,539,540,verkhnyaya inta,70.97,65.9811,60.3094,54,18,11.50,RU,1659618066
548,548,549,kokomo,73.35,40.4864,-86.1336,88,0,6.91,US,1659618069

In [9]:
# create new simplified DF to add hotel name to
hotel_df = df_ideal[["City", "Country", "Latitude", "Longitude"]]
hotel_df["Hotel Name"] = ""
hotel_df = hotel_df.reset_index()
del hotel_df["index"]
hotel_df

/var/folders/sp/6plkjdmn5qsb1910x_z26fnm0000gn/T/ipykernel_76181/4179913525.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hotel_df["Hotel Name"] = ""

                 City Country  Latitude  Longitude Hotel Name
0     bambous virieux      MU  -20.3428    57.7575
1               vaini      TO  -21.2000  -175.2000
2              castro      BR  -24.7911   -50.0119
3          winnemucca      US   40.9730  -117.7357
4   sao joao da barra      BR  -21.6403   -41.0511
5         east london      ZA  -33.0153    27.9116
6      saint-philippe      RE  -21.3585    55.7679
7      guerrero negro      MX   27.9769  -114.0611
8             lincoln      US   40.8000   -96.6670
9           mahebourg      MU  -20.4081    57.7000
10           souillac      MU  -20.5167    57.5167
11             bayevo      RU   53.2833    80.7667
12           rebrikha      RU   53.0733    82.3408
13           billings      US   45.7833  -108.5007
14        grand gaube      MU  -20.0064    57.6608
15              bowen      AU  -20.0167   148.2333
16             namibe      AO  -15.1961    12.1522
17           at-bashi      KG   41.1702    75.8106
18            parabel      RU   58.6978    81.4825
19          alyangula      AU  -13.8483   136.4192
20        polovinnoye      RU   54.7914    65.9864
21             kaltan      RU   53.5347    87.2457
22             tshane      BW  -24.0196    21.8684
23           plouzane      FR   48.3833    -4.6167
24       ponta grossa      BR  -25.0950   -50.1619
25    verkhnyaya inta      RU   65.9811    60.3094
26             kokomo      US   40.4864   -86.1336

In [10]:
# create empty list to be filled in following for loop 
hotel_name = []

In [11]:
# define base url and parameters for searching within the gmap api
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "radius": 5000,
    "keyword": "hotel",
    "types": "hotel",
    "key": g_key
}

# complete loop through the DF to find closest hotel to the provided city center coordinates
for index, row in hotel_df.iterrows():
    city = row["City"]
    print(f"Retrieving Results for {index}, the closest hotel to {city} is: ")
    lat = row["Latitude"]
    lng = row["Longitude"]
    params["location"] = f"{lat}, {lng}"
    response = requests.get(base_url, params = params)
    hotel_data = response.json()
    
    # try and except the results from the above API request and append the list with successful requests
    try:
        hotel_name.append(hotel_data["results"][0]["name"])
        print(f"{hotel_name[index]}")
    except:
        print("------------")
        print("No Hotel found") 
        print("------------")
        hotel_name.append("NO HOTEL NEARBY")

Retrieving Results for 0, the closest hotel to bambous virieux is:
La Case du Pêcheur
Retrieving Results for 1, the closest hotel to vaini is:
Dayspring Lodge
Retrieving Results for 2, the closest hotel to castro is:
Buganville Palace Hotel
Retrieving Results for 3, the closest hotel to winnemucca is:
Holiday Inn Express Winnemucca, an IHG Hotel
Retrieving Results for 4, the closest hotel to sao joao da barra is:
Pousada Porto Prime
Retrieving Results for 5, the closest hotel to east london is:
Garden Court East London
Retrieving Results for 6, the closest hotel to saint-philippe is:
Hôtel Les Embruns Du Baril
Retrieving Results for 7, the closest hotel to guerrero negro is:
Hotel TerraSal
Retrieving Results for 8, the closest hotel to lincoln is:
Hampton Inn Lincoln - South/Heritage Park
Retrieving Results for 9, the closest hotel to mahebourg is:
Holiday Inn Mauritius Mon Tresor
Retrieving Results for 10, the closest hotel to souillac is:
Shanti Maurice Resort & Spa
Retrieving Results for 11, the closest hotel to bayevo is:
------------
No Hotel found
------------
Retrieving Results for 12, the closest hotel to rebrikha is:
Гостиница "Уют"
Retrieving Results for 13, the closest hotel to billings is:
Days Inn by Wyndham Billings
Retrieving Results for 14, the closest hotel to grand gaube is:
St Antoinne appartments
Retrieving Results for 15, the closest hotel to bowen is:
Whitsunday Sands Resort
Retrieving Results for 16, the closest hotel to namibe is:
Hotel Chik Chik Namibe
Retrieving Results for 17, the closest hotel to at-bashi is:
Hostel At-Bashy
Retrieving Results for 18, the closest hotel to parabel is:
Gostinitsa Berloga
Retrieving Results for 19, the closest hotel to alyangula is:
Groote Eylandt Lodge
Retrieving Results for 20, the closest hotel to polovinnoye is:
------------
No Hotel found
------------
Retrieving Results for 21, the closest hotel to kaltan is:
гостиница City
Retrieving Results for 22, the closest hotel to tshane is:
------------
No Hotel found
------------
Retrieving Results for 23, the closest hotel to plouzane is:
Belvedere
Retrieving Results for 24, the closest hotel to ponta grossa is:
Barbur Plaza Hotel Ponta Grossa
Retrieving Results for 25, the closest hotel to verkhnyaya inta is:
------------
No Hotel found
------------
Retrieving Results for 26, the closest hotel to kokomo is:
Hampton Inn & Suites Kokomo

In [12]:
# add hotel list to the empty column in the dataframe
hotel_df["Hotel Name"] = hotel_name
hotel_df

,City,Country,Latitude,Longitude,Hotel Name
0,bambous virieux,MU,-20.3428,57.7575,La Case du Pêcheur
1,vaini,TO,-21.2000,-175.2000,Dayspring Lodge
2,castro,BR,-24.7911,-50.0119,Buganville Palace Hotel
3,winnemucca,US,40.9730,-117.7357,"Holiday Inn Express Winnemucca, an IHG Hotel"
4,sao joao da barra,BR,-21.6403,-41.0511,Pousada Porto Prime
5,east london,ZA,-33.0153,27.9116,Garden Court East London
6,saint-philippe,RE,-21.3585,55.7679,Hôtel Les Embruns Du Baril
7,guerrero negro,MX,27.9769,-114.0611,Hotel TerraSal
8,lincoln,US,40.8000,-96.6670,Hampton Inn Lincoln - South/Heritage Park
9,mahebourg,MU,-20.4081,57.7000,Holiday Inn Mauritius Mon Tresor
10,souillac,MU,-20.5167,57.5167,Shanti Maurice Resort & Spa
11,bayevo,RU,53.2833,80.7667,NO HOTEL NEARBY
12,rebrikha,RU,53.0733,82.3408,"Гостиница ""Уют"""
13,billings,US,45.7833,-108.5007,Days Inn by Wyndham Billings
14,grand gaube,MU,-20.0064,57.6608,St Antoinne appartments
15,bowen,AU,-20.0167,148.2333,Whitsunday Sands Resort
16,namibe,AO,-15.1961,12.1522,Hotel Chik Chik Namibe
17,at-bashi,KG,41.1702,75.8106,Hostel At-Bashy
18,parabel,RU,58.6978,81.4825,Gostinitsa Berloga
19,alyangula,AU,-13.8483,136.4192,Groote Eylandt Lodge
20,polovinnoye,RU,54.7914,65.9864,NO HOTEL NEARBY
21,kaltan,RU,53.5347,87.2457,гостиница City
22,tshane,BW,-24.0196,21.8684,NO HOTEL NEARBY
23,plouzane,FR,48.3833,-4.6167,Belvedere
24,ponta grossa,BR,-25.0950,-50.1619,Barbur Plaza Hotel Ponta Grossa
25,verkhnyaya inta,RU,65.9811,60.3094,NO HOTEL NEARBY
26,kokomo,US,40.4864,-86.1336,Hampton Inn & Suites Kokomo

In [13]:
 # redisplay humidity Heatmap layer
fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 5)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# create DF for LAT/LONG to be used in graph
locations_hotels = hotel_df[["Latitude", "Longitude"]].astype(float)
locations_hotels

    Latitude  Longitude
0   -20.3428    57.7575
1   -21.2000  -175.2000
2   -24.7911   -50.0119
3    40.9730  -117.7357
4   -21.6403   -41.0511
5   -33.0153    27.9116
6   -21.3585    55.7679
7    27.9769  -114.0611
8    40.8000   -96.6670
9   -20.4081    57.7000
10  -20.5167    57.5167
11   53.2833    80.7667
12   53.0733    82.3408
13   45.7833  -108.5007
14  -20.0064    57.6608
15  -20.0167   148.2333
16  -15.1961    12.1522
17   41.1702    75.8106
18   58.6978    81.4825
19  -13.8483   136.4192
20   54.7914    65.9864
21   53.5347    87.2457
22  -24.0196    21.8684
23   48.3833    -4.6167
24  -25.0950   -50.1619
25   65.9811    60.3094
26   40.4864   -86.1336

In [15]:
# convert columns to lists
#cities_list = hotel_df["City"].tolist()
#country_list = hotel_df["Country"].tolist()

In [16]:
# use info box template provided in starter code
info_box_template= """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [17]:
hotel_layer = gmaps.symbol_layer(
    locations_hotels, fill_color='rgba(0, 150, 0, 0.4)',
    stroke_color='rgba(0, 0, 150, 0.4)', scale=7,
    info_box_content= hotel_info)
fig = gmaps.figure()
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
 # Create a combined map
fig = gmaps.figure()

fig.add_layer(heat_layer)
fig.add_layer(hotel_layer)

fig

Figure(layout=FigureLayout(height='420px'))